captain_console/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('about/', include('about.urls')),
    path('accounts/',include('accounts.urls')),
    path('cart/',include('cart.urls'))
]

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='cart-index'),
    path('checkout', views.checkout, name='checkout-index'),
    path('payment', views.payment, name="payment-index"),
    path('review', views.review, name="review-index"),
    path('confirm', views.confirm_order, name="confirm-order")
]

cart/models.py
from django.db import models
from products.models import Product
from django.contrib.auth.models import User
from django.utils import timezone
from django_countries.fields import CountryField

MONTHS_CHOICES= (
    ("01", "01"),
    ("02", "02"),
    ("03", "03"),
    ("04", "04"),
    ("05", "05"),
    ("06", "06"),
    ("07", "07"),
    ("08", "08"),
    ("09", "09"),
    ("10", "10"),
    ("11", "11"),
    ("12", "12")
)

YEAR_CHOICES = (
    ('2020', '2020'),
    ('2021', '2021'),
    ('2022', '2022'),
    ('2023', '2023'),
    ('2024', '2024'),
    ('2025', '2025'),
    ('2026', '2026'),
    ('2027', '2027'),
    ('2028', '2028'),

)


class OrderItem(models.Model):
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.name}"

    def get_item_total_price(self):
        return self.quantity * self.item.price


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(default=timezone.now)
    order_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    dismissed = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.id} - {self.user.username}"

    def get_order_total_price(self):
        total = 0
        for item in self.items.all():
            total += item.get_item_total_price()

        return total

    def confirm_order(self):
        self.ordered = True


class OrderContactInfo(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    country = CountryField()
    postal_code = models.CharField(max_length=255)

    def __str__(self):
        return f"Order id: {self.order.id}, Owner: {self.first_name} {self.last_name}"


class OrderPaymentInfo(models.Model):
    order = models.OneToOneField(Order, on_delete=models.CASCADE)
    card_number = models.CharField(max_length=19)
    cardholder_name = models.CharField(max_length=255)
    cvc = models.CharField(max_length=3)
    expiry_month = models.CharField(
        max_length=2,
        choices=MONTHS_CHOICES,
        default='01'
    )
    expiry_year = models.CharField(
        max_length=4,
        choices=YEAR_CHOICES,
        default='1'
    )

products/models.py
from django.db import models
from django.urls import reverse


class ProductCategory(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=999)

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=999, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=999, blank=True)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    price = models.FloatField()
    on_sale = models.BooleanField()
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    slug = models.SlugField()

    def __str__(self):
        return self.name

    def get_add_to_cart_url(self):
        return reverse('add-to-cart', kwargs={
            'slug': self.slug
        })

    def get_remove_one_cart(self):
        return reverse('remove-one-cart', kwargs={
            'slug': self.slug
        })

    def get_remove_all_item_cat(self):
        return reverse('remove-all-item-cart', kwargs={
            'slug': self.slug
        })


class ProductImage(models.Model):
    image = models.CharField(max_length=999)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.image

cart/forms/contact_form.py
from django.forms import ModelForm, widgets
from cart.models import OrderContactInfo
from django import forms


class ContactInformationForm(ModelForm):

    def clean_first_name(self):
        data = self.cleaned_data['first_name']
        for i in data:
            if not i.isalpha():
                raise forms.ValidationError('Invalid first name!')

        return data

    def clean_last_name(self):
        data = self.cleaned_data['last_name']
        for i in data:
            if not i.isalpha():
                raise forms.ValidationError('Invalid last name!')

        return data

    class Meta:
        model = OrderContactInfo
        exclude = ('order',)
        widgets = {
            'first_name': widgets.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'First name'
            }),
            'last_name': widgets.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Last Name'
            }),
            'address': widgets.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Address'
            }),
            'city': widgets.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'City'
            }),
            'country': widgets.Select(attrs={
                'class': 'custom-select',
            }),
            'postal_code': widgets.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Postal code'
            })
        }

cart/forms/payment_form.py
from django.forms import ModelForm, widgets
from cart.models import OrderPaymentInfo
from django import forms


class PaymentInformationForm(ModelForm):

    def clean_cardholder_name(self):
        data = self.cleaned_data['cardholder_name']
        for i in data:
            if not i.isalpha() and not i.isspace():
                raise forms.ValidationError('Invalid name!')

        return data

    def clean_card_number(self):
        data = self.cleaned_data['card_number']
        # The lowest possible credit-card number is a MAESTRO UK which is
        if len(data) < 12:
            raise forms.ValidationError('Invalid credit card!')

        return data

    def clean_cvc(self):
        data = self.cleaned_data['cvc']
        if len(data) != 3:
            raise forms.ValidationError('Invalid CVC!')

        return data

    class Meta:
        model = OrderPaymentInfo
        exclude = ('order',)
        widgets = {
            'card_number': widgets.TextInput(attrs={
                'class': 'form-control',
                'placeholder':'Credit Card',
                'type':'number',
                'min_length':'15'
            }),
            'cardholder_name': widgets.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Cardholder name',
                'type':'text'
            }),
            'cvc': widgets.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'CVC',
                'type':'number'
            }),
            'expiry_month': widgets.Select(attrs={
                'class':'custom-select'
            }),
            'expiry_year': widgets.Select(attrs={
                'class': 'custom-select'
            })
        }

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from cart.models import Order, OrderItem, OrderContactInfo, OrderPaymentInfo
from products.models import Product
from django.utils import timezone
from django.db.models import F
from django.contrib.auth.decorators import login_required
from cart.forms.contact_form import ContactInformationForm
from cart.forms.payment_form import PaymentInformationForm
from django.contrib import messages


@login_required
def index(request):
    order_qs = Order.objects.filter(user=request.user, ordered=False, dismissed=False)
    context = {
        'orders': order_qs
    }
    return render(request, 'cart/index.html', context)


@login_required
def checkout(request):
    '''Renders the checkout phase and the
    contact information form.
    '''
    order_qs = Order.objects.filter(user=request.user, ordered=False, dismissed=False)
    order = order_qs[0]
    order_contact = OrderContactInfo.objects.get_or_create(order=order)
    order_contact_test = order_contact[0]
    context = {
        'orders': order_qs,
        'contact_form': ContactInformationForm(instance=order_contact_test)
    }
    if request.method == 'POST':
        contact_form = ContactInformationForm(instance=order_contact_test, data=request.POST)
        if contact_form.is_valid():
            contact_info = contact_form.save(commit=False)
            contact_info.save()
            return redirect('payment-index')
        else:
            messages.warning(request, 'Invalid contact information!')

    return render(request, 'cart/checkout.html', context)


@login_required
def payment(request):
    '''Renders the payment view and
    shows the payment information form.
    '''
    order_qs = Order.objects.filter(user=request.user, ordered=False, dismissed=False)
    order = order_qs[0]
    order_payment = OrderPaymentInfo.objects.get_or_create(order=order)
    order_payment_instance = order_payment[0]
    context = {
        'orders': order_qs,
        'payment_form': PaymentInformationForm(instance=order_payment_instance)
    }
    if request.method == 'POST':
        payment_form = PaymentInformationForm(instance=order_payment_instance, data=request.POST)
        if payment_form.is_valid():
            payment_info = payment_form.save(commit=False)
            payment_info.save()
            return redirect('review-index')
        else:
            messages.warning(request, 'Invalid Payment information.')

    return render(request, 'cart/payment.html', context)


@login_required
def review(request):
    '''Renders the review page with
    all the required information.
    '''
    order_qs = Order.objects.filter(user=request.user, ordered=False, dismissed=False)
    order_contact_qs = OrderContactInfo.objects.filter(order=order_qs[0])
    order_payment_qs = OrderPaymentInfo.objects.filter(order=order_qs[0])
    context = {
        'order': order_qs[0],
        'order_contact': order_contact_qs[0],
        'order_payment': order_payment_qs[0]
    }
    return render(request, 'cart/confirmation.html', context)


@login_required
def confirm_order(request):
    '''Marks the order as ordered and sets
    the ordered date to the current time.
    '''
    order_qs = Order.objects.filter(user=request.user, ordered=False, dismissed=False)
    order = order_qs[0]
    order.ordered = True
    order.order_date = timezone.now()
    order.save()
    messages.success(request, 'Order with the id {} was placed.'.format(order.id))
    return redirect('home-index')


@login_required
def add_to_cart(request, slug):
    '''Adds the item to the cart or increases the amount of
    that item in the cart.
    '''
    item = get_object_or_404(Product, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(item=item, user=request.user)
    order_qs = Order.objects.filter(user=request.user, ordered=False, dismissed=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity = F('quantity') + 1
            order_item.save()
            messages.success(request, 'Item was added to your cart.')
        else:
            order.items.add(order_item)
            messages.success(request, 'Item was added to your cart.')
        return redirect('product-index')
    else:  # Creates the order if this is the first item added into the cart.
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user, order_date=ordered_date)
        order.items.add(order_item)
        messages.success(request, 'Item was added to your cart.')
    return redirect('product-index')


@login_required
def remove_one_item_from_cart(request, slug):
    '''Removes one item from the cart.
    '''
    item = get_object_or_404(Product, slug=slug)
    order_item = OrderItem.objects.get(
        item=item,
        user=request.user,
        is_ordered=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False, dismissed=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            if order_item.quantity > 1:
                order_item.quantity = F('quantity') - 1
                order_item.save()
            else:
                order.items.remove(order_item)
                order_item.delete()
                if not order.items.filter(
                        user=request.user):  # checks if the cart is emptied and dismissed the order if so.
                    order.dismissed = True
                    order.save()

    return redirect('cart-index')

templates/cart/checkout.html
{% extends 'base.html' %}
{% block title %}
    <title>Cart</title>
{% endblock %}
{% block content %}
    <div class="container d-flex shadow-border m-4 p-5">
        <div class="col-8 mr-2">
            <div class="row border-bottom border-dark">
                <h4>Order Summary</h4>
            </div>
            {% for order in orders %}
                {% for order_item in order.items.all %}
                    <div class="row d-flex mt-5">
                        <div class="col-6 d-flex align-items-start">
                            <div class="row profile2-row">
                                <div class="col">
                                    {{ order_item.quantity }} x of {{ order_item.item.name }}
                                    $ {{ order_item.get_item_total_price|floatformat:2 }}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}
            <div class="row d-flex">
                <div class="col p-0 d-flex justify-content-start">
                    {% for order in orders %}
                        <span class="mt-5 align-text-bottom">Total price: ${{ order.get_order_total_price|floatformat:2 }}</span>
                    {% endfor %}
                </div>
            </div>

        </div>

        <form class="form form-horizontal col border-left border-dark pr-3" method="post">
            <div class="row ml-2">
                <h4>Contact Information</h4>
            </div>
            {% csrf_token %}
            <div class="form-group form-row">
                <div class="col">
                    {{ contact_form.first_name }}
                </div>

            </div>
            <div class="form-group form-row">
                <div class="col">
                    {{ contact_form.last_name }}
                </div>
            </div>
            <div class="form-group form-row">
                <div class="col">
                    {{ contact_form.address }}
                </div>
            </div>
            <div class="form-group form-row">
                <div class="col">
                    {{ contact_form.postal_code }}
                </div>
            </div>
            <div class="form-group form-row">
                <div class="col">
                    {{ contact_form.city }}
                </div>
            </div>
            <div class="form-group form-row">

            </div>
            <div class="form-group form-row">
                <div class="col">
                    Country: {{ contact_form.country }}
                </div>
            </div>
            <a href="{% url 'cart-index' %}" class="btn btn-warning mt-2">Go Back</a>
            <input type="submit" class="btn btn-primary mt-2" value="Proceed to payment"/>
        </form>
    </div>
    </div>
{% endblock %}

templates/cart/confirmation.html
{% extends 'base.html' %}
{% block title %}
    <title>Cart</title>
{% endblock %}
{% block content %}
    <div class="container d-flex mt-5 shadow-border p-5">
        <div class="col">
            {% for item in order.items.all %}
                <div class="row">
                    <p>{{ item.item.name }} x {{ item.quantity }} - ${{ item.get_item_total_price|floatformat:2 }}</p>
                </div>
            {% endfor %}
            <div class="row font-weight-bold">Total price: ${{ order.get_order_total_price|floatformat:2 }}</div>
        </div>
        <div class="col border-left border-dark pl-5">
            <div class="row">
                <p>Name: {{ order_contact.first_name }} {{ order_contact.last_name }}</p>
            </div>
            <div class="row">
                <p>Address: {{ order_contact.address }}</p>
            </div>
            <div class="row">
                <p>City: {{ order_contact.city }}</p>
            </div>
            <div class="row">
                <p>Postal Code: {{ order_contact.postal_code }}</p>
            </div>
            <div class="row">
                <p>Country: {{ order_contact.country }}</p>
            </div>
        </div>
        <div class="col border-left border-dark pl-5">
            <div class="row">
                <p>Card number: {{ order_payment.card_number }}</p>
            </div>
            <div class="row">
                <p>Cardholder name: {{ order_payment.cardholder_name }}</p>
            </div>
            <div class="row">
                <p>Expiry date: {{ order_payment.expiry_month }}/{{ order_payment.expiry_year }}</p>
            </div>
            <div class="row">
                <p>CVC: {{ order_payment.cvc }}</p>
            </div>
        </div>
    </div>
    <div>
        <a href="{% url 'payment-index' %}" class="btn btn-warning mt-2">Go Back</a>
        <a href="{% url 'confirm-order' %}" class="btn btn-primary mt-2">Confirm</a>
    </div>

    </div>

{% endblock %}

templates/cart/index.html
{% extends 'base.html' %}
{% block title %}
    <title>Cart</title>
{% endblock %}
{% block content %}
    <div class="container shadow-border m-4 p-5">
        <div class="row border-bottom border-dark">
            <h3>Cart</h3>
        </div>
        {% if orders.exists %}
            {% for order in orders %}
                {% for order_item in order.items.all %}
                    <div class="row d-flex mt-5">
                        <div class="col-3 product-img-box d-flex align-items-center border border-dark">
                            <img src="{{ order_item.item.productimage_set.first }}" class="product-img">
                        </div>
                        <div class="col">
                            <div class="row profile2-row">
                                <div class="col-12">
                                    {{ order_item.quantity }} x of {{ order_item.item.name }}
                                    $ {{ order_item.get_item_total_price|floatformat:2 }}
                                </div>
                            </div>
                            <div class="row d-flex mt-5 justify-content-end">
                                <div class="justify-content-end"><a href="{{ order_item.item.get_remove_one_cart }}"
                                                                    class="btn btn-danger">Remove</a>
                                </div>
                            </div>
                            <div class="row d-flex mt-2 mb-5 justify-content-end">
                                <div class="justify-content-end"><a href="{{ order_item.item.get_add_to_cart_url }}"
                                                                    class="btn btn-success">Add one</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}
            <div class="row d-flex">
                <div class="col p-0 d-flex justify-content-end">
                    {% for order in orders %}
                        <span class="mt-5 align-text-bottom">Total price: ${{ order.get_order_total_price|floatformat:2 }}</span>
                    {% endfor %}
                    <a href="{% url 'checkout-index' %}" class="btn btn-primary mt-5 ml-2">Proceed to checkout</a>
                </div>
            </div>
        {% else %}
            <div class="row font-weight-bold">Your cart is empty!</div>
            <div class="row">
                <a href="{% url 'product-index' %}" class="btn btn-primary mt-3">Go back to store</a>
            </div>
        {% endif %}

{% endblock %}

templates/cart/payment.html
{% extends 'base.html' %}
{% block title %}
    <title>Cart</title>
{% endblock %}
{% block content %}
    <div class="d-flex container shadow-border m-5 p-5">
        <div class="col-8 mr-2">
            <div class="row border-bottom border-dark">
                <h4>Order Summary</h4>
            </div>
            {% for order in orders %}
                {% for order_item in order.items.all %}
                    <div class="row d-flex mt-5">
                        <div class="col-6 d-flex align-items-start">
                            <div class="row profile2-row">
                                <div class="col">
                                    {{ order_item.quantity }} x of {{ order_item.item.name }}
                                    $ {{ order_item.get_item_total_price|floatformat:2 }}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endfor %}
            <div class="row d-flex">
                <div class="col p-0 d-flex justify-content-start">
                    {% for order in orders %}
                        <span class="mt-5 align-text-bottom">Total price: ${{ order.get_order_total_price|floatformat:2 }}</span>
                    {% endfor %}
                </div>
            </div>
        </div>
        <form class="form form-horizontal col border-left border-dark pr-3" method="post">
            <div class="row ml-2">
                <h4>Payment Information</h4>
            </div>
            {% csrf_token %}
            <div class="form-group form-row">
                <div class="col">
                    {{ payment_form.card_number }}
                </div>
            </div>
            <div class="form-group form-row">
                <div class="col">
                    {{ payment_form.cardholder_name }}
                    {{ payment_form.errors }}
                </div>
            </div>
            <div class="form-group form-row">
                <div class="col">
                    {{ payment_form.cvc }}
                </div>
            </div>
            <div class="form-inline form-row">
                <div class="col-3">
                    {{ payment_form.expiry_month }}
                </div>
                <div class="col-4">
                    {{ payment_form.expiry_year }}
                </div>
                <div class="col">Expiry date</div>
            </div>
            <a href="{% url 'checkout-index' %}" class="btn btn-warning mt-2">Go Back</a>
            <input type="submit" class="btn btn-primary mt-2" value="Review Order"/>
        </form>
    </div>
    </div>
{% endblock %}